/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c2cab0",
        "primary-fixed-dim": "#98da27",
        "secondary": "#45dfa4",
        "on-primary-fixed-variant": "#334f00",
        "surface-container": "#1c201f",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#653e00",
        "on-tertiary": "#472a00",
        "on-primary-fixed": "#121f00",
        "on-tertiary-fixed": "#2a1700",
        "primary-container": "#a3e635",
        "tertiary-fixed": "#ffddb8",
        "outline-variant": "#424936",
        "on-error": "#690005",
        "secondary-fixed": "#68fcbf",
        "on-secondary": "#003825",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-lowest": "#0b0f0e",
        "inverse-primary": "#446900",
        "surface-container-low": "#181c1b",
        "tertiary": "#ffecd9",
        "surface-dim": "#101413",
        "on-primary": "#213600",
        "secondary-container": "#00bd85",
        "secondary-fixed-dim": "#45dfa4",
        "surface-bright": "#363a39",
        "surface-tint": "#98da27",
        "on-background": "#e0e3e1",
        "surface": "#101413",
        "on-secondary-fixed-variant": "#005137",
        "on-secondary-container": "#00452e",
        "on-surface": "#e0e3e1",
        "on-primary-container": "#416400",
        "surface-container-high": "#272b2a",
        "tertiary-container": "#ffc989",
        "error": "#ffb4ab",
        "on-tertiary-container": "#805000",
        "inverse-surface": "#e0e3e1",
        "on-secondary-fixed": "#002114",
        "outline": "#8c947c",
        "primary-fixed": "#b2f746",
        "surface-variant": "#323634",
        "inverse-on-surface": "#2d3130",
        "background": "#101413",
        "surface-container-highest": "#323634",
        "primary": "#ccff80"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin": "1rem",
        "margin-desktop": "3rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "margin-tablet": "2rem",
        "gutter": "1.25rem",
        "gutter-desktop": "1.75rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-xl": "2.5rem"
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "title-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"]
      }
    }
  },
  plugins: [],
}
